[package]
name = "rust-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
env_logger = "0.11.5"
log = "0.4.22"
mio = { version = "1.0.2", features = ["os-poll", "net"] }
slab = "0.4.9"
